### ISSUE TITLE
Casper.page.content adds html tags for non-html content types

### ISSUE THREAD

**Issue by n1k0** [casperjs/casperjs#178]
We should add a `getPageContent()` method to casper to access raw body contents when response content-type is _not_ `text/html`.

**Comment by tobeorla** [comment]
Why this issue is closed? This bug remains unfixed and "view-source:" hack doesn't work.

**Comment by dotmechanize** [comment]
This issue does not appear to be fixed. Any updates?

When requesting pure JSON from a known good (serves up only JSON) URL I also get the HTML tags mentioned above.

**Comment by istr** [comment]
This is fixed in master, see [the test proving it](https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/content.js).

NOTE however, that you need your server to deliver the correct ```Content-Type``` header (```application/json```) -- there is no content sniffing whatsoever.

**Comment by dotmechanize** [comment]
Thanks for the feedback. I'll have to give it a try.

For what it's worth, I discovered that the problem was intermittent. In cases where the returned JSON was not 'prettified' all worked well. If I set my server's JSON output to be 'pretty' then the HTML tags appeared and caused JSON.parse() to fail.  My workaround has been to simply strip out all HTML with a regex before attempting to create a JSON object. This approach is working for me.

**Comment by entrptaher** [comment]
This is not fixed yet.
Only if somehow this is implemented, that'd be great.

```js
JSON.parse(this.getPageContent().replace(/<\/?[^>]+(>|$)/g, ""));
```

**Comment by istr** [comment]
@entrptaher Could you explain what you mean with your code snippet and/or a test case that demonstrates this still does not work? Did you verify that your server returns the correct `Content-Type` header? (see above)

**Comment by istr** [comment]
@dotmechanize 
> If I set my server's JSON output to be 'pretty' then the HTML tags appeared and caused JSON.parse() to fail.

Are you sure that setting the "prettify" option did not change the response's `Content-Type` header?

**Comment by entrptaher** [comment]
# CODE 1(Works as Expected)
```js
var casper = require('casper')
    .create();

casper.start();
casper.open('http://localhost/');
casper.echo("...");
casper.then(function dumpHeaders() {
    this.currentResponse.headers.forEach(function (header) {
        console.log(header.name + ': ' + header.value);
    });
});
casper.then(function getthecontents() {
    console.log(this.getPageContent());
});
casper.run(function () {
    this.exit();
});
```
##Output: ```
...
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 2
ETag: W/"2-mZFLkyvTelC5g8XnyQrpOw"
Date: Sat, 14 May 2016 11:25:19 GMT
Connection: keep-alive
{"one": "two","key": "value"}
```
#CODE 2(Works as expected)
```js
var port = 6100;
var casper = require("casper")
    .create();
var jsonrules = 'http://localhost/';
casper.start(jsonrules);
casper.run(function () {
    console.log('...');
});
require("webserver")
    .create()
    .listen(port, function (request, response) {
                response.statusCode = 200;
                response.write(casper.getPageContent());
                response.close();
    })
console.log("listening on port", port);
```
## Output 
```
{"one": "two","key": "value"}
```
#CODE 3 (Server times out, used code 4 as workaround)
```js
var port = 6100;
var casper = require("casper")
    .create();
var jsonrules = 'http://localhost/';
casper.start(jsonrules);
casper.run(function () {
    console.log('...');
});
require("webserver")
    .create()
    .listen(port, function (request, response) {
      casper.open(jsonrules)
                .then(function () {
                    casper.then(function dumpHeaders() {
                        this.currentResponse.headers.forEach(function (header) {
                            console.log(header.name + ': ' + header.value);
                        });
                    });
                    this.then(function () {
                        this.echo(this.getPageContent());
                    });
                })
                .then(function () {
                    response.statusCode = 200;
                    response.write('OK');
                    response.close();
                })
/*
// Doesn't work either
casper.open(jsonrules)
                .then(function () {
                    response.statusCode = 200;
                    response.write(this.getPageContent());
                    response.close();
                })
*/
    })
console.log("listening on port", port);
```
# CODE 4(Doesn 't Work)
```js
var port = 6100;
var casper = require("casper")
    .create();
var jsonrules = 'http://localhost/';
casper.start(jsonrules);
casper.run(function () {
    console.log('...');
});
require("webserver")
    .create()
    .listen(port, function (request, response) {
        casper.steps = [];
        casper.step = 0;
        if(request.url.indexOf("/openseseme") !== -1) {
            casper.open(jsonrules)
                .then(function () {
                    casper.then(function dumpHeaders() {
                        this.currentResponse.headers.forEach(function (header) {
                            console.log(header.name + ': ' + header.value);
                        });
                    });
                    this.then(function () {
                        this.echo(this.getPageContent());
                    });
                })
                .then(function () {
                    response.statusCode = 200;
                    response.write('OK');
                    response.close();
                })
        }
        casper.run();
    })
console.log("listening on port", port);
```
##Output: 
```
listening on port 6100
...
X-Powered-By: Express
ETag: W/"2-mZFLkyvTelC5g8XnyQrpOw"
Date: Sat, 14 May 2016 11:22:10 GMT
Connection: keep-alive
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"one": "two","key": "value"}</pre></body></html>
```

**Comment by istr** [comment]
> ##Output:
> 
> listening on port 6100
> ...
> X-Powered-By: Express
> ETag: W/"2-mZFLkyvTelC5g8XnyQrpOw"
> Date: Sat, 14 May 2016 11:22:10 GMT
> Connection: keep-alive

Yes, exactly like expected. Your express server does not include the correct `Content-Type` header here.

The default implied `Content-Type` when the server does not provide it, is `text/html`. 

**No content type sniffing is performed** on CasperJS side. This is up to you. Fix your server or sniff the content type on your own.

**Comment by entrptaher** [comment]
This is to let you know that **all of those scripts had same target url**. And the page **does** have Application/json otherwise the first and second code wouldn't work as expected, nor they would print what happens.

**Comment by istr** [comment]
As the current behavior seems to be counter-intuitive and was the reason for multiple issues raised, I would like to discuss if we should change the behavior, provide `Casper.prototype.getPagePlainText` along with `Casper.prototype.getPageContent` and clearly document that `getPageContent` will always return HTML, like the engine does. @BIGjuevos @mickaelandrieu ?

**Comment by istr** [comment]
@entrptaher 
> And the page does have Application/json

But *not* in the failing example. Please try to replace the call to `this.getPageContent()` with `this.page.framePlainText` in your example and see if this works for you. If so, it is definitely the missing `Content-Type` in the failing case.

**Comment by entrptaher** [comment]
The issue might be related to this part of code where I used casper.start outside the webserver. The code didn't work and I had to do a quick workaround by using,
```js
casper.steps = [];
casper.step = 0;
```

The getPageContent() fails there.

**Comment by entrptaher** [comment]
Only this four lines could do the trick?

```js
Casper.prototype.getPlainText = function getPageContent() {
    "use strict";
    this.checkStarted();
    return this.page.framePlainText;
};
```

**Comment by mickaelandrieu** [comment]
@entrptaher go for a pull request with a test, thank you for your researches :)

**Comment by istr** [comment]
> Firefox/Chrome/Any other browser renders the page as JSON, no matter how many times I reload them, if casperjs uses phantomjs and phantomjs is a browser, then casperjs (and phantomjs) should provide some solution for those who gets into such silly problems.

Yes, you're kind of right. PhantomJS is a browser, but with its own deviations. Even though PhantomJS, Chrome, and Safari all build on (different versions) of Webkit they behave wildly different in several edge/corner cases. Firefox is a completely different story.

I have a different idea, though, that might more helpful while testing: check if the response contains a `Content-Type` header and emit a warning that clearly states what will be the consequences. #1584

**Comment by entrptaher** [comment]
Now, some awesome discovery~~ -_- 
```fetchText('html')``` and ```getPlainText()``` is same. 
Their tests shows same results. Maybe we don't need getPlainText() but rather we can create an example of using fetchText('html') for non-html types? Because they are both basically getting what the browser is showing.

**Comment by istr** [comment]
> The browser automatically adds html tags, casper doesn't do that

Yes, like stated in my comment above: 
https://github.com/casperjs/casperjs/issues/178#issuecomment-219219505 (last sentence of the EDIT).

> a nice solution called fetchText('html') for raw page data

I guess the point is, that this solution is not so very nice (it is not obvious at all) and not well documented. And as far as I can tell (need to re-check, I might be wrong here) there is a slight difference:
- `fetchText('html')` fetches the serialized and concatenated DOM  text nodes while
- `this.page.framePlainText` returns the actual (unprocessed) response text

with the effect that the former should have sanitized / normalized entities while the latter has not (in case it is an HTML document).

So I still think we would be better off with the "four lines [that] could do the trick", because these would be obvious, even for newcomers to CasperJS.

**Comment by entrptaher** [comment]
Looks like you're correct,
![](http://i.imgur.com/plCnpOC.png)

It seems, I still have a long way to go.

**Comment by kensoh** [comment]
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.
